
#include "AnimationData.h"

SpriteAnim<ImageAsset> AnimationData::DEATH("death", 10, Resources::DEATH.DEATH_000, Resources::DEATH.DEATH_001, Resources::DEATH.DEATH_002, Resources::DEATH.DEATH_003, Resources::DEATH.DEATH_004, Resources::DEATH.DEATH_005);
SpriteAnim<ImageAsset> AnimationData::KYO_CROUCH("kyo_crouch", 15, Resources::KYO_CROUCH.FRAME0, Resources::KYO_CROUCH.FRAME1, Resources::KYO_CROUCH.FRAME2);
SpriteAnim<ImageAsset> AnimationData::KYO_LITTLE_FIST("kyo_little_fist", 13, Resources::KYO_LITTLE_FIST.FRAME0, Resources::KYO_LITTLE_FIST.FRAME1, Resources::KYO_LITTLE_FIST.FRAME2, Resources::KYO_LITTLE_FIST.FRAME3);
SpriteAnim<ImageAsset> AnimationData::KYO_LITTLE_KICK("kyo_little_kick", 20, Resources::KYO_LITTLE_KICK.FRAME0, Resources::KYO_LITTLE_KICK.FRAME1, Resources::KYO_LITTLE_KICK.FRAME2, Resources::KYO_LITTLE_KICK.FRAME3, Resources::KYO_LITTLE_KICK.FRAME3, Resources::KYO_LITTLE_KICK.FRAME4, Resources::KYO_LITTLE_KICK.FRAME5, Resources::KYO_LITTLE_KICK.FRAME6, Resources::KYO_LITTLE_KICK.FRAME7);
SpriteAnim<ImageAsset> AnimationData::KYO_IDLE("kyo_idle", 8, Resources::KYO_IDLE.FRAME0, Resources::KYO_IDLE.FRAME1, Resources::KYO_IDLE.FRAME2, Resources::KYO_IDLE.FRAME3, Resources::KYO_IDLE.FRAME4, Resources::KYO_IDLE.FRAME5, Resources::KYO_IDLE.FRAME6, Resources::KYO_IDLE.FRAME7, Resources::KYO_IDLE.FRAME8);
SpriteAnim<ImageAsset> AnimationData::KYO_JUMP("kyo_jump", 25, Resources::KYO_JUMP.FRAME0, Resources::KYO_JUMP.FRAME1, Resources::KYO_JUMP.FRAME2, Resources::KYO_JUMP.FRAME3, Resources::KYO_JUMP.FRAME4, Resources::KYO_JUMP.FRAME5, Resources::KYO_JUMP.FRAME6, Resources::KYO_JUMP.FRAME7, Resources::KYO_JUMP.FRAME8, Resources::KYO_JUMP.FRAME9);
SpriteAnim<ImageAsset> AnimationData::KYO_JUMP_BACK("kyo_jump_back", 20, Resources::KYO_JUMP_BACK.FRAME0, Resources::KYO_JUMP_BACK.FRAME1, Resources::KYO_JUMP_BACK.FRAME2, Resources::KYO_JUMP_BACK.FRAME3);
SpriteAnim<ImageAsset> AnimationData::KYO_MOVE_BACK("kyo_move_back", 10, Resources::KYO_MOVE_BACK.FRAME0, Resources::KYO_MOVE_BACK.FRAME1, Resources::KYO_MOVE_BACK.FRAME2, Resources::KYO_MOVE_BACK.FRAME3, Resources::KYO_MOVE_BACK.FRAME4, Resources::KYO_MOVE_BACK.FRAME5);
SpriteAnim<ImageAsset> AnimationData::KYO_MOVE_FORWARD("kyo_move_forward", 10, Resources::KYO_MOVE_FORWARD.FRAME0, Resources::KYO_MOVE_FORWARD.FRAME1, Resources::KYO_MOVE_FORWARD.FRAME2, Resources::KYO_MOVE_FORWARD.FRAME3, Resources::KYO_MOVE_FORWARD.FRAME4);
SpriteAnim<ImageAsset> AnimationData::KYO_ORYU("kyo_oryu", 10, Resources::KYO_ORYU.FRAME0, Resources::KYO_ORYU.FRAME1, Resources::KYO_ORYU.FRAME2, Resources::KYO_ORYU.FRAME3, Resources::KYO_ORYU.FRAME4, Resources::KYO_ORYU.FRAME5, Resources::KYO_ORYU.FRAME6, Resources::KYO_ORYU.FRAME7, Resources::KYO_ORYU.FRAME8, Resources::KYO_ORYU.FRAME9, Resources::KYO_ORYU.FRAME10);
SpriteAnim<ImageAsset> AnimationData::KYO_ROLL_BACKWARD("kyo_roll_backward", 20, Resources::KYO_ROLL_BACKWARD.FRAME0, Resources::KYO_ROLL_BACKWARD.FRAME1, Resources::KYO_ROLL_BACKWARD.FRAME2, Resources::KYO_ROLL_BACKWARD.FRAME3, Resources::KYO_ROLL_BACKWARD.FRAME4, Resources::KYO_ROLL_BACKWARD.FRAME5, Resources::KYO_ROLL_BACKWARD.FRAME6, Resources::KYO_ROLL_BACKWARD.FRAME7, Resources::KYO_ROLL_BACKWARD.FRAME8);
SpriteAnim<ImageAsset> AnimationData::KYO_ROLL_FORWARD("kyo_roll_forward", 20, Resources::KYO_ROLL_FORWARD.FRAME0, Resources::KYO_ROLL_FORWARD.FRAME1, Resources::KYO_ROLL_FORWARD.FRAME2, Resources::KYO_ROLL_FORWARD.FRAME3, Resources::KYO_ROLL_FORWARD.FRAME4, Resources::KYO_ROLL_FORWARD.FRAME5, Resources::KYO_ROLL_FORWARD.FRAME6, Resources::KYO_ROLL_FORWARD.FRAME7, Resources::KYO_ROLL_FORWARD.FRAME8);
SpriteAnim<ImageAsset> AnimationData::KYO_RUN("kyo_run", 10, Resources::KYO_RUN.FRAME0, Resources::KYO_RUN.FRAME1, Resources::KYO_RUN.FRAME2, Resources::KYO_RUN.FRAME3, Resources::KYO_RUN.FRAME4, Resources::KYO_RUN.FRAME5, Resources::KYO_RUN.FRAME6, Resources::KYO_RUN.FRAME7, Resources::KYO_RUN.FRAME8);
SpriteAnim<ImageAsset> AnimationData::KYO_SALUTE("kyo_salute", 7, Resources::KYO_SALUTE.FRAME0, Resources::KYO_SALUTE.FRAME1, Resources::KYO_SALUTE.FRAME2, Resources::KYO_SALUTE.FRAME3, Resources::KYO_SALUTE.FRAME4, Resources::KYO_SALUTE.FRAME5, Resources::KYO_SALUTE.FRAME6, Resources::KYO_SALUTE.FRAME7, Resources::KYO_SALUTE.FRAME8, Resources::KYO_SALUTE.FRAME9, Resources::KYO_SALUTE.FRAME10, Resources::KYO_SALUTE.FRAME11, Resources::KYO_SALUTE.FRAME12, Resources::KYO_SALUTE.FRAME13, Resources::KYO_SALUTE.FRAME14, Resources::KYO_SALUTE.FRAME15, Resources::KYO_SALUTE.FRAME16);

    
